export const BOARD = [
  [
    { value: "Joker", occupiedColor: "", isSequence: false },
    { value: "10♠", occupiedColor: "", isSequence: false },
    { value: "9♠", occupiedColor: "", isSequence: false },
    { value: "8♠", occupiedColor: "", isSequence: false },
    { value: "7♠", occupiedColor: "", isSequence: false },
    { value: "7♦", occupiedColor: "", isSequence: false },
    { value: "8♦", occupiedColor: "", isSequence: false },
    { value: "9♦", occupiedColor: "", isSequence: false },
    { value: "10♦", occupiedColor: "", isSequence: false },
    { value: "Joker", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "10♣", occupiedColor: "", isSequence: false },
    { value: "K♠", occupiedColor: "", isSequence: false },
    { value: "6♠", occupiedColor: "", isSequence: false },
    { value: "5♠", occupiedColor: "", isSequence: false },
    { value: "4♠", occupiedColor: "", isSequence: false },
    { value: "4♦", occupiedColor: "", isSequence: false },
    { value: "5♦", occupiedColor: "", isSequence: false },
    { value: "6♦", occupiedColor: "", isSequence: false },
    { value: "K♦", occupiedColor: "", isSequence: false },
    { value: "10♥", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "9♣", occupiedColor: "", isSequence: false },
    { value: "6♣", occupiedColor: "", isSequence: false },
    { value: "Q♠", occupiedColor: "", isSequence: false },
    { value: "3♠", occupiedColor: "", isSequence: false },
    { value: "2♠", occupiedColor: "", isSequence: false },
    { value: "2♦", occupiedColor: "", isSequence: false },
    { value: "3♦", occupiedColor: "", isSequence: false },
    { value: "Q♥", occupiedColor: "", isSequence: false },
    { value: "6♥", occupiedColor: "", isSequence: false },
    { value: "9♥", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "8♣", occupiedColor: "", isSequence: false },
    { value: "5♣", occupiedColor: "", isSequence: false },
    { value: "3♣", occupiedColor: "", isSequence: false },
    { value: "Q♣", occupiedColor: "", isSequence: false },
    { value: "A♠", occupiedColor: "", isSequence: false },
    { value: "A♦", occupiedColor: "", isSequence: false },
    { value: "Q♦", occupiedColor: "", isSequence: false },
    { value: "3♥", occupiedColor: "", isSequence: false },
    { value: "5♥", occupiedColor: "", isSequence: false },
    { value: "8♥", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "7♣", occupiedColor: "", isSequence: false },
    { value: "4♣", occupiedColor: "", isSequence: false },
    { value: "2♣", occupiedColor: "", isSequence: false },
    { value: "A♣", occupiedColor: "", isSequence: false },
    { value: "K♣", occupiedColor: "", isSequence: false },
    { value: "K♥", occupiedColor: "", isSequence: false },
    { value: "A♥", occupiedColor: "", isSequence: false },
    { value: "2♥", occupiedColor: "", isSequence: false },
    { value: "4♥", occupiedColor: "", isSequence: false },
    { value: "7♥", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "7♥", occupiedColor: "", isSequence: false },
    { value: "4♥", occupiedColor: "", isSequence: false },
    { value: "2♥", occupiedColor: "", isSequence: false },
    { value: "A♥", occupiedColor: "", isSequence: false },
    { value: "K♥", occupiedColor: "", isSequence: false },
    { value: "K♣", occupiedColor: "", isSequence: false },
    { value: "A♣", occupiedColor: "", isSequence: false },
    { value: "2♣", occupiedColor: "", isSequence: false },
    { value: "4♣", occupiedColor: "", isSequence: false },
    { value: "7♣", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "8♥", occupiedColor: "", isSequence: false },
    { value: "5♥", occupiedColor: "", isSequence: false },
    { value: "3♥", occupiedColor: "", isSequence: false },
    { value: "Q♦", occupiedColor: "", isSequence: false },
    { value: "A♦", occupiedColor: "", isSequence: false },
    { value: "A♠", occupiedColor: "", isSequence: false },
    { value: "Q♣", occupiedColor: "", isSequence: false },
    { value: "3♣", occupiedColor: "", isSequence: false },
    { value: "5♣", occupiedColor: "", isSequence: false },
    { value: "8♣", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "9♥", occupiedColor: "", isSequence: false },
    { value: "6♥", occupiedColor: "", isSequence: false },
    { value: "Q♥", occupiedColor: "", isSequence: false },
    { value: "3♦", occupiedColor: "", isSequence: false },
    { value: "2♦", occupiedColor: "", isSequence: false },
    { value: "2♠", occupiedColor: "", isSequence: false },
    { value: "3♠", occupiedColor: "", isSequence: false },
    { value: "Q♠", occupiedColor: "", isSequence: false },
    { value: "6♣", occupiedColor: "", isSequence: false },
    { value: "9♣", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "10♥", occupiedColor: "", isSequence: false },
    { value: "K♦", occupiedColor: "", isSequence: false },
    { value: "6♦", occupiedColor: "", isSequence: false },
    { value: "5♦", occupiedColor: "", isSequence: false },
    { value: "4♦", occupiedColor: "", isSequence: false },
    { value: "4♠", occupiedColor: "", isSequence: false },
    { value: "5♠", occupiedColor: "", isSequence: false },
    { value: "6♠", occupiedColor: "", isSequence: false },
    { value: "K♠", occupiedColor: "", isSequence: false },
    { value: "10♣", occupiedColor: "", isSequence: false },
  ],
  [
    { value: "Joker", occupiedColor: "", isSequence: false },
    { value: "10♦", occupiedColor: "", isSequence: false },
    { value: "9♦", occupiedColor: "", isSequence: false },
    { value: "8♦", occupiedColor: "", isSequence: false },
    { value: "7♦", occupiedColor: "", isSequence: false },
    { value: "7♠", occupiedColor: "", isSequence: false },
    { value: "8♠", occupiedColor: "", isSequence: false },
    { value: "9♠", occupiedColor: "", isSequence: false },
    { value: "10♠", occupiedColor: "", isSequence: false },
    { value: "Joker", occupiedColor: "", isSequence: false },
  ],
];
