export const BOARD = [
  [
    { value: "Joker", occupiedColor: "" },
    { value: "10♠", occupiedColor: "" },
    { value: "9♠", occupiedColor: "" },
    { value: "8♠", occupiedColor: "" },
    { value: "7♠", occupiedColor: "" },
    { value: "7♦", occupiedColor: "" },
    { value: "8♦", occupiedColor: "" },
    { value: "9♦", occupiedColor: "" },
    { value: "10♦", occupiedColor: "" },
    { value: "Joker", occupiedColor: "" },
  ],
  [
    { value: "10♣", occupiedColor: "" },
    { value: "K♠", occupiedColor: "" },
    { value: "6♠", occupiedColor: "" },
    { value: "5♠", occupiedColor: "" },
    { value: "4♠", occupiedColor: "" },
    { value: "4♦", occupiedColor: "" },
    { value: "5♦", occupiedColor: "" },
    { value: "6♦", occupiedColor: "" },
    { value: "K♥", occupiedColor: "" },
    { value: "10♥", occupiedColor: "" },
  ],
  [
    { value: "9♣", occupiedColor: "" },
    { value: "6♣", occupiedColor: "" },
    { value: "Q♠", occupiedColor: "" },
    { value: "3♠", occupiedColor: "" },
    { value: "2♠", occupiedColor: "" },
    { value: "2♦", occupiedColor: "" },
    { value: "3♦", occupiedColor: "" },
    { value: "Q♥", occupiedColor: "" },
    { value: "6♥", occupiedColor: "" },
    { value: "9♥", occupiedColor: "" },
  ],
  [
    { value: "8♣", occupiedColor: "" },
    { value: "5♣", occupiedColor: "" },
    { value: "3♣", occupiedColor: "" },
    { value: "Q♣", occupiedColor: "" },
    { value: "A♠", occupiedColor: "" },
    { value: "A♦", occupiedColor: "" },
    { value: "Q♦", occupiedColor: "" },
    { value: "3♥", occupiedColor: "" },
    { value: "5♥", occupiedColor: "" },
    { value: "8♥", occupiedColor: "" },
  ],
  [
    { value: "7♣", occupiedColor: "" },
    { value: "4♣", occupiedColor: "" },
    { value: "2♣", occupiedColor: "" },
    { value: "A♣", occupiedColor: "" },
    { value: "K♣", occupiedColor: "" },
    { value: "K♦", occupiedColor: "" },
    { value: "A♥", occupiedColor: "" },
    { value: "2♥", occupiedColor: "" },
    { value: "4♥", occupiedColor: "" },
    { value: "7♥", occupiedColor: "" },
  ],
  [
    { value: "7♥", occupiedColor: "" },
    { value: "4♥", occupiedColor: "" },
    { value: "2♥", occupiedColor: "" },
    { value: "A♥", occupiedColor: "" },
    { value: "K♥", occupiedColor: "" },
    { value: "K♣", occupiedColor: "" },
    { value: "A♣", occupiedColor: "" },
    { value: "2♣", occupiedColor: "" },
    { value: "4♣", occupiedColor: "" },
    { value: "7♣", occupiedColor: "" },
  ],
  [
    { value: "8♥", occupiedColor: "" },
    { value: "5♥", occupiedColor: "" },
    { value: "3♥", occupiedColor: "" },
    { value: "Q♦", occupiedColor: "" },
    { value: "A♦", occupiedColor: "" },
    { value: "A♠", occupiedColor: "" },
    { value: "Q♣", occupiedColor: "" },
    { value: "3♣", occupiedColor: "" },
    { value: "5♣", occupiedColor: "" },
    { value: "8♣", occupiedColor: "" },
  ],
  [
    { value: "9♥", occupiedColor: "" },
    { value: "6♥", occupiedColor: "" },
    { value: "Q♥", occupiedColor: "" },
    { value: "3♦", occupiedColor: "" },
    { value: "2♦", occupiedColor: "" },
    { value: "2♠", occupiedColor: "" },
    { value: "3♠", occupiedColor: "" },
    { value: "Q♠", occupiedColor: "" },
    { value: "6♣", occupiedColor: "" },
    { value: "9♣", occupiedColor: "" },
  ],
  [
    { value: "10♥", occupiedColor: "" },
    { value: "K♦", occupiedColor: "" },
    { value: "6♦", occupiedColor: "" },
    { value: "5♦", occupiedColor: "" },
    { value: "4♦", occupiedColor: "" },
    { value: "4♠", occupiedColor: "" },
    { value: "5♠", occupiedColor: "" },
    { value: "6♠", occupiedColor: "" },
    { value: "K♠", occupiedColor: "" },
    { value: "10♣", occupiedColor: "" },
  ],
  [
    { value: "Joker", occupiedColor: "" },
    { value: "10♦", occupiedColor: "" },
    { value: "9♦", occupiedColor: "" },
    { value: "8♦", occupiedColor: "" },
    { value: "7♦", occupiedColor: "" },
    { value: "7♠", occupiedColor: "" },
    { value: "8♠", occupiedColor: "" },
    { value: "9♠", occupiedColor: "" },
    { value: "10♠", occupiedColor: "" },
    { value: "Joker", occupiedColor: "" },
  ],
];
